services:
  - type: web
    name: task-management-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api-docs
    autoDeploy: true

databases:
  - name: task-management-db
    databaseName: task_management_db
    user: task_management_user
    plan: free 